// <auto-generated />
namespace ShowTime.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Moviecontext7 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Moviecontext7));
        
        string IMigrationMetadata.Id
        {
            get { return "201810251220443_Moviecontext7"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
